### ISSUE TITLE
我是mac上的 node9.0 咋跑不起来呢

### ISSUE THREAD

**Issue by yoohan-dex** [zhuweiyou/weixin-headimg#1]
![image](https://user-images.githubusercontent.com/7565496/33196438-13605d3c-d11a-11e7-8bec-f6e3a071d595.png)

**Comment by zhuweiyou** [comment]
报错是 `images` 这个模块的，你换成 node 8.x 试一下，我拿 mac 机器 8.x 可以跑起来：

![image](https://user-images.githubusercontent.com/8413791/33197140-923f05b4-d11e-11e7-9a8a-aa52b6583ce8.png)

**Comment by yoohan-dex** [comment]
@zhuweiyou 换8后是可以了 不过 buffer可以拉取下来吗？ 我这边把图片下完后发现body里面都是空的

**Comment by zhuweiyou** [comment]
buffer 你可以 fs.writeFile 存到本地，或者 images 的 save()

body 空的，你先打印下前面的图片 URL ，检查下是否正确获取

**Comment by yoohan-dex** [comment]
@zhuweiyou 
![image](https://user-images.githubusercontent.com/7565496/33198825-51f5ee0a-d128-11e7-84e3-8646f3d2c540.png)
这个判断是有效的吗？我这边只能改成判断有没有response里面的MemberLIst有没有东西来做

**Comment by zhuweiyou** [comment]
member list 就是这个 API 返回的，所以这个判断是等这个请求返回数据以后做操作。
你把完整的返回内容打印出来看下。

**Comment by zhuweiyou** [comment]
onResponse 会监听所有的 response 事件，这个判断是等这个接口返回以后做操作，member list 就是它返回的

**Comment by yoohan-dex** [comment]
@zhuweiyou 如果按照这个indexOf来判断 永远都不会true诶
我对比了所有的url里也没发现有webwxgetcontact的字段

**Comment by zhuweiyou** [comment]
要微信扫码的，你扫了吗。你重新下载我源码，稍微修改了一下，之前的 debug 没打印出来

**Comment by yoohan-dex** [comment]
@zhuweiyou 扫了的 不过我现在在重新install依赖 刚刚我直接切node8 也不知道是不是有影响

**Comment by zhuweiyou** [comment]
扫码了等一会 就会请求这个接口，你可以在弹出的 chrome 打开开发者工具 看下有没有请求。（页面可以手动刷新）

**Comment by yoohan-dex** [comment]
@zhuweiyou 我找到问题了
![image](https://user-images.githubusercontent.com/7565496/33199258-7e360714-d12a-11e7-8109-7a4c029c1e27.png)
不知道是不是微信会变？
不过即使如此 也没有自动生成成功 我再找找看问题是什么

**Comment by zhuweiyou** [comment]
那其实可以不判断这么多，只要判断 /cgi-bin/.. webwxgetcontact? 包含就好。它域名有两个 wx 和 wx2

**Comment by yoohan-dex** [comment]
@zhuweiyou 嗯 确实 我固定为wx后就可以下下来了 不过偶尔会报错 - 。-

**Comment by zhuweiyou** [comment]
现在可以合成了吗？

**Comment by zhuweiyou** [comment]
偶尔会报错，这个不用在意了，再跑一次就好。。反正是自己用 ╮(╯▽╰)╭

**Comment by yoohan-dex** [comment]
@zhuweiyou 还有个问题喔 好友比较多 取到的图片很多空头像，可以怎么解决？把请求放慢有用吗？

**Comment by zhuweiyou** [comment]
请求放慢可以尝试一下，另外在得到空的时候可以重试请求。
